apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cons1persec
  name: cons100
spec:
  serviceName: "cons1persecservice"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: cons1persec
  template:
    metadata:
      labels:
        app: cons1persec
    spec:
      containers:
        - name: cons1persec
          image: docker.io/mezzeddine/consumerstickyenvpass:v24 # sticky
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic1
            - name: GROUP_ID
              value: testgroup1
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLEEP
              value: "10"
            - name: POLL
              value: "95"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: THENAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=100
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cons1persec
  name: cons200
spec:
  serviceName: "cons1persecservice"
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      app: cons1persec
  template:
    metadata:
      labels:
        app: cons1persec
    spec:
      containers:
        - name: cons1persec
          image: docker.io/mezzeddine/consumerstickyenvpass:v24 # sticky
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic1
            - name: GROUP_ID
              value: testgroup1
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLEEP
              value: "10"
            - name: POLL
              value: "95"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: THENAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=100